services:
  sentiment-mlflow:
    container_name: sentiment-mlflow
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../mlruns:/mlruns
      - ../artifacts:/artifacts
    environment:
      - MLFLOW_TRACKING_URI=http://localhost:5000
      - MLFLOW_ARTIFACT_ROOT=/artifacts
    command: >
      mlflow server 
      --host 0.0.0.0 
      --port 5000 
      --backend-store-uri /mlruns 
      --default-artifact-root file:///artifacts
    networks:
      - mlflow-network

  sentiment-api:
    container_name: sentiment-api
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - sentiment-mlflow
    volumes:
      - ../mlruns:/mlruns
      - ../artifacts:/artifacts
    environment:
      - MLFLOW_TRACKING_URI=http://sentiment-mlflow:5000
      - MLFLOW_ARTIFACT_ROOT=/artifacts
    networks:
      - mlflow-network

networks:
  mlflow-network:
    name: mlflow-network
    driver: bridge