data:
  dataset_name: "imdb"
  train_size: 0.8
  random_state: 42

model:
  vectorizer:
    max_features: 5000  # Add this default
    max_features_options: [1000, 5000, 10000]  # Grid search options
    min_df: 5
    max_df: 0.7
  classifier:
    type: "logistic_regression"
    params:
      C: 1.0  # Add this default value
      C_options: [0.1, 1.0, 10.0]  # Grid search options
      max_iter: 1000  # Add this default value
      max_iter_options: [100, 500, 1000]  # Grid search options

mlflow:
  tracking_uri: "http://sentiment-mlflow:5000"
  experiment_name: "sentiment_analysis"

api:
  host: "0.0.0.0"
  port: 8000