name: MLflow Sync

on:
  push:
    branches: [ main ]

jobs:
  sync-mlflow:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
    
    - name: Create MLflow artifacts
      run: |
        python -c "
        import pandas as pd
        import json
        import os
        
        # Create artifacts directory
        os.makedirs('github_artifacts', exist_ok=True)
        
        try:
            # Read the actual results from file
            with open('src/results/model_results.json', 'r') as f:
                results = json.load(f)
            
            # Create artifacts from actual results
            best_run = {
                'run_id': 'best_run',
                'experiment_id': '1',
                **results['best_params'],
                **results['metrics']
            }
            
            pd.DataFrame([best_run]).to_csv('github_artifacts/champion_model.csv', index=False)
            
            # Save all runs
            all_runs = []
            for params, score in zip(results['all_results']['params'], 
                                   results['all_results']['scores']):
                run_data = {
                    'params': params,
                    'score': score
                }
                all_runs.append(run_data)
            
            pd.DataFrame(all_runs).to_csv('github_artifacts/hyperparameter_tuning_results.csv', index=False)
            print('Successfully created artifacts')
            
        except Exception as e:
            print(f'Error creating artifacts: {str(e)}')
            raise
        "
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-artifacts
        path: github_artifacts/