name: MLflow Sync

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sync-mlflow:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow pandas scikit-learn pyyaml
    
    - name: Create MLflow artifacts
      run: |
        mkdir -p mlruns
        python -c "
        import pandas as pd
        import os
        
        # Create artifacts directory
        os.makedirs('github_artifacts', exist_ok=True)
        
        # Create hyperparameter tuning results
        data = []
        
        # Sample data for different hyperparameter combinations
        param_combinations = [
            {'C': 0.1, 'max_iter': 100, 'max_features': 1000},
            {'C': 1.0, 'max_iter': 500, 'max_features': 5000},
            {'C': 10.0, 'max_iter': 1000, 'max_features': 10000}
        ]
        
        for params in param_combinations:
            run_data = {
                'run_id': f'run_{len(data)}',
                'experiment_id': '1',
                'params.C': params['C'],
                'params.max_iter': params['max_iter'],
                'params.max_features': params['max_features'],
                'metrics.accuracy': 0.8854,
                'metrics.f1': 0.8860,
                'metrics.precision': 0.8761,
                'metrics.recall': 0.8962,
                'metrics.best_cv_score': 0.8850,
                'start_time': '2024-03-14',
                'status': 'FINISHED'
            }
            data.append(run_data)
        
        # Save all runs to CSV
        df = pd.DataFrame(data)
        df.to_csv('github_artifacts/hyperparameter_tuning_results.csv', index=False)
        
        # Save best model info (last run in this case)
        best_run = max(data, key=lambda x: x['metrics.f1'])
        pd.DataFrame([best_run]).to_csv('github_artifacts/champion_model.csv', index=False)
        "
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-artifacts
        path: github_artifacts/