name: MLflow Sync

on:
  push:
    branches: [ main ]

jobs:
  sync-mlflow:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow pandas scikit-learn
    
    - name: Create artifacts from MLflow
      run: |
        python -c "
        import mlflow
        import pandas as pd
        
        # Get MLflow experiment and runs
        mlflow.set_tracking_uri('mlruns')  # Use local mlruns directory
        experiment = mlflow.get_experiment_by_name('sentiment_analysis')
        runs = mlflow.search_runs(experiment_ids=[experiment.experiment_id])
        
        # Save all runs data
        runs.to_csv('github_artifacts/hyperparameter_tuning_results.csv', index=False)
        
        # Get best run (highest f1 score)
        best_run = runs.sort_values('metrics.f1', ascending=False).iloc[0]
        pd.DataFrame([best_run]).to_csv('github_artifacts/champion_model.csv', index=False)
        "
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-artifacts
        path: github_artifacts/